# Generated by Django 2.2.3 on 2019-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_heading', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_image', models.FileField(upload_to='media/project_image/')),
                ('project_description', models.TextField(max_length=5000)),
                ('project_github_url', models.CharField(blank=True, max_length=300, null=True)),
                ('project_bitbucket_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
